[WIP] Delphiの学習（高根沢）
htakanezawa/takanezawa-it-nasu.com pull request #1
Opened 2020-04-14 07:55 UTC by htakanezawa

### 概要
Dephiの学習の為に、下記チュートリアル
で簡単な実装を行いました。そのPRです。
https://qiita.com/kazaiso/items/b3941a234853b9cb6abb
https://qiita.com/kazaiso/items/c76eac60bdd4dd075fa3
https://qiita.com/kazaiso/items/5d6b58966a00e91ae198

2020-04-15 01:19 UTC, htakanezawa commented
一旦WIPにします。

2020-04-21 09:31 UTC, akm commented
@htakanezawa WIP になっていますが、レビュアに設定されたので先にコメントしておきます。

https://github.com/htakanezawa/takanezawa-it-nasu.com/pull/1#issue-403027516 には、解説をまとめた言葉が書かれていますが、これらは実際のコードのどこに当てはまるのでしょうか？

コミットから読み取ろうと思いましたが `継承について` が継承を使っているということ以外はわかりませんでした

- [隠蔽について](https://github.com/htakanezawa/takanezawa-it-nasu.com/pull/1/commits/ee10bae510c9ead9b1555555912ade660f55ba35)
- [継承の基礎？](https://github.com/htakanezawa/takanezawa-it-nasu.com/pull/1/commits/1a139ea159322ea84306805bc2ef15bba932b9c0)
- [継承について](https://github.com/htakanezawa/takanezawa-it-nasu.com/pull/1/commits/c7b490b61475b1827bb4b8e3a747afed7714e734)
- [継承の応用？](https://github.com/htakanezawa/takanezawa-it-nasu.com/pull/1/commits/6ff5ac87d4de7735d54e624be57e7cc41b69af1d)

学習して理解できたことを確認するためにPull Requestを作ってもらうことは前回の週次開発会議でお話したと思いますが、その確認のためのコミットメッセージに `？` が付いているのは、わかっていないことを示してますよね？

僕には `？` をつけた意図が `わかっていないけどチュートリアルに書いてあることやってるんでOKですよね？` という風に見えてしまいます。

学習の途中ならば理解していない状態は誰にでもあることは承知していますが、わかっていないのであれば何がわかっていないのかをはっきりさせ、調べたり質問して期待しているゴールに着実に進んでいることを見せてください。理解していることが確認できないままではPull RequestをApproveすることはありません。

2020-05-07 03:44 UTC, akm commented
@htakanezawa  WIPが外れているので、レビューします。

https://github.com/htakanezawa/takanezawa-it-nasu.com/pull/1#issuecomment-617066730 に
> #1 (comment) には、解説をまとめた言葉が書かれていますが、これらは実際のコードのどこに当てはまるのでしょうか？

と書きましたが、これについての返事はまだもらっていないと思っています。

https://github.com/htakanezawa/takanezawa-it-nasu.com/pull/1#issue-403027516 にたくさん書いてあることが、実際のソースコードのどこの話をしているのかわかりません。

説明することが難しければ、ソースコード中に説明するコメントを書いてください。

2020-05-07 03:45 UTC, akm requested changes
@htakanezawa  WIPが外れているので、レビューします。

https://github.com/htakanezawa/takanezawa-it-nasu.com/pull/1#issuecomment-617066730 に
> #1 (comment) には、解説をまとめた言葉が書かれていますが、これらは実際のコードのどこに当てはまるのでしょうか？

と書きましたが、これについての返事はまだもらっていないと思っています。

https://github.com/htakanezawa/takanezawa-it-nasu.com/pull/1#issue-403027516 にたくさん書いてあることが、実際のソースコードのどこの話をしているのかわかりません。

説明することが難しければ、ソースコード中に説明するコメントを書いてください。

2020-06-03 00:44 UTC, htakanezawa commented
@akm 

> #1 (comment) にたくさん書いてあることが、実際のソースコードのどこの話をしているのかわかりません。

> 説明することが難しければ、ソースコード中に説明するコメントを書いてください。

申し訳ありません。
ソースコード中に説明するコメントを書くようにします。

2020-06-15 09:51 UTC, htakanezawa commented
@akm @tecyokomichi @yama-zaki 
ソースコードにコメントを入れました。
お手数ですが、ご確認お願い致します。

2020-06-16 05:35 UTC, akm commented
@htakanezawa 再レビューを依頼するときは `Re-request review` するようにお願いします。

<img width="328" alt="スクリーンショット 2020-06-16 14 33 07 午後" src="https://user-images.githubusercontent.com/18912/84735478-983daa00-afde-11ea-8e25-f4862f5eba26.png">

2020-06-16 05:51 UTC, akm approved these changes
@htakanezawa 元の資料の内容を写しただけに見えるので、これで理解できているかどうかを判断することは難しいです。

次は、何かオリジナルのコードで、クラスや継承について解説を入れて書いてみてはいかがでしょうか？

2020-06-23 00:35 UTC, yama-zaki approved these changes

2020-06-30 23:32 UTC, tecyokomichi approved these changes

2020-06-30 23:32 UTC, merged